"""ETF/股票自动投前研究引擎。"""

from qteasy_research.pretrade.orchestrator import (
    continue_research,
    run_instrument_research,
)
from qteasy_research.pretrade.schemas import (
    AssetIdentity,
    AssetDynamicSnapshot,
    AssetFactorResult,
    AssetProfile,
    PortfolioAssetContext,
    ResearchConfig,
    ResearchDecision,
    ResearchNote,
    ResearchProject,
    ResearchExportResult,
    ResearchReportDraft,
    ResearchProjectType,
    ResearchAssetReference,
    ResearchProjectStatus,
    ResearchRunResult,
    ResearchStatus,
    DataQualityMetadata,
    TransactionCostConfig,
    FactorDefinition,
    FactorResearchResult,
    AssetFactorExposure,
    FactorMatchResult,
    FactorScoreResult,
)
from qteasy_research.pretrade.providers import (
    AssetDataSnapshot,
    CleanDataProvider,
    ProviderData,
    SqliteProvider,
)
from qteasy_research.pretrade.data_manager import (
    DataManager,
    DataQueryResult,
    DataSourceHealth,
    DataSyncRequest,
    DataSyncResult,
    FactorBuildResult,
    HttpMiddlewareProvider,
)
from qteasy_research.pretrade.factor_data import (
    FactorDataProvider,
    FactorDataResponse,
    FactorObservation,
    filter_point_in_time,
)
from qteasy_research.pretrade.factor_research import (
    FACTOR_RESEARCH_FORMULA_VERSION,
    diagnose_factor_collinearity,
    estimate_asset_factor_exposure,
    estimate_transaction_cost,
    evaluate_factor_effectiveness,
    grade_data_quality,
    monitor_factor_decay,
)
from qteasy_research.pretrade.factor_catalog import (
    ASSET_FACTOR_CATALOG,
    MACRO_THEMES,
    build_theme_weights,
    list_factor_catalog,
)
from qteasy_research.pretrade.technical import (
    FORMULA_VERSION,
    TechnicalIndicatorConfig,
    analyze_technical_indicators,
)
from qteasy_research.pretrade.projects import (
    add_project_decision,
    add_project_note,
    add_asset_reference,
    archive_research_project,
    close_research_project,
    compare_research_versions,
    create_research_project,
    create_strategy_project,
    delete_project_decision,
    delete_project_note,
    delete_asset_reference,
    delete_research_report,
    discard_report_draft,
    get_research_project,
    list_project_decisions,
    list_project_notes,
    list_project_versions,
    get_report_draft,
    list_asset_references,
    list_research_projects,
    reopen_research_project,
    restore_research_report,
    save_report_draft,
    update_project_decision,
    update_project_note,
    update_research_project,
    update_project_portfolio_assets,
    list_project_portfolio_assets,
    list_portfolio_asset_contexts,
    update_portfolio_asset_context,
)
from qteasy_research.asset_profiles import (
    analyze_asset_factors,
    compare_asset_reports,
    get_asset_dynamic_snapshot,
    get_asset_profile,
    get_latest_asset_report,
    list_asset_factor_snapshots,
    list_asset_profile_snapshots,
    list_asset_reports,
)
from qteasy_research.pretrade.factors import FACTOR_FORMULA_VERSION
from qteasy_research.pretrade.display import metadata_display_rows, metadata_field_label, metadata_value_label
from qteasy_research.pretrade.export import (
    export_project_report,
    export_report_bundle,
    export_research_report,
)
from qteasy_research.pretrade.factor_scoring import (
    calculate_factor_scores,
    formula_md5,
    monitor_factor_long_short,
)
from qteasy_research.pretrade.factor_ui import (
    DEFAULT_FACTOR_DEFINITIONS,
    get_factor_data_status,
    initialize_default_factor_definitions,
)
from qteasy_research.strategy_import import (
    StrategyAnalysis,
    analyze_strategy_file,
    generate_strategy_candidate,
    save_strategy_analysis,
    run_generated_strategy_backtest,
)

__all__ = [
    "AssetIdentity",
    "AssetProfile",
    "AssetDynamicSnapshot",
    "AssetFactorResult",
    "PortfolioAssetContext",
    "ResearchConfig",
    "ResearchDecision",
    "ResearchNote",
    "ResearchProject",
    "ResearchExportResult",
    "ResearchReportDraft",
    "ResearchProjectType",
    "ResearchAssetReference",
    "ResearchProjectStatus",
    "ResearchRunResult",
    "ResearchStatus",
    "DataQualityMetadata",
    "TransactionCostConfig",
    "FactorDefinition",
    "FactorResearchResult",
    "AssetFactorExposure",
    "FactorMatchResult",
    "FactorScoreResult",
    "AssetDataSnapshot",
    "CleanDataProvider",
    "ProviderData",
    "SqliteProvider",
    "DataManager",
    "DataQueryResult",
    "DataSourceHealth",
    "DataSyncRequest",
    "DataSyncResult",
    "FactorBuildResult",
    "HttpMiddlewareProvider",
    "FactorDataProvider",
    "FactorDataResponse",
    "FactorObservation",
    "filter_point_in_time",
    "FACTOR_RESEARCH_FORMULA_VERSION",
    "evaluate_factor_effectiveness",
    "estimate_transaction_cost",
    "grade_data_quality",
    "diagnose_factor_collinearity",
    "monitor_factor_decay",
    "estimate_asset_factor_exposure",
    "MACRO_THEMES",
    "ASSET_FACTOR_CATALOG",
    "list_factor_catalog",
    "build_theme_weights",
    "research_factor",
    "estimate_exposure",
    "match_factors",
    "analyze_factor_collinearity",
    "analyze_factor_decay",
    "FORMULA_VERSION",
    "TechnicalIndicatorConfig",
    "analyze_technical_indicators",
    "continue_research",
    "run_instrument_research",
    "add_project_decision",
    "add_project_note",
    "add_asset_reference",
    "archive_research_project",
    "close_research_project",
    "compare_research_versions",
    "create_research_project",
    "create_strategy_project",
    "delete_project_decision",
    "delete_project_note",
    "delete_asset_reference",
    "delete_research_report",
    "discard_report_draft",
    "get_research_project",
    "list_project_decisions",
    "list_project_notes",
    "list_project_versions",
    "get_report_draft",
    "list_asset_references",
    "list_research_projects",
    "reopen_research_project",
    "restore_research_report",
    "save_report_draft",
    "update_project_decision",
    "update_project_note",
    "update_research_project",
    "update_project_portfolio_assets",
    "list_project_portfolio_assets",
    "update_portfolio_asset_context",
    "list_portfolio_asset_contexts",
    "get_asset_profile",
    "list_asset_profile_snapshots",
    "get_asset_dynamic_snapshot",
    "analyze_asset_factors",
    "list_asset_factor_snapshots",
    "list_asset_reports",
    "get_latest_asset_report",
    "compare_asset_reports",
    "FACTOR_FORMULA_VERSION",
    "metadata_display_rows",
    "metadata_field_label",
    "metadata_value_label",
    "export_research_report",
    "export_project_report",
    "export_report_bundle",
    "calculate_factor_scores",
    "formula_md5",
    "monitor_factor_long_short",
    "DEFAULT_FACTOR_DEFINITIONS",
    "get_factor_data_status",
    "initialize_default_factor_definitions",
    "StrategyAnalysis",
    "analyze_strategy_file",
    "generate_strategy_candidate",
    "save_strategy_analysis",
    "run_generated_strategy_backtest",
]


def __getattr__(name: str):
    """延迟加载实验室 API，避免 ``qteasy_research.factor_lab`` 的循环导入。"""

    if name in {
        "research_factor", "estimate_exposure", "match_factors", "import_factor_research_result",
        "analyze_factor_collinearity", "analyze_factor_decay",
    }:
        from qteasy_research import factor_lab

        return getattr(factor_lab, name)
    raise AttributeError(name)
